services:
  auth-postgres:
    image: postgres:17
    container_name: auth-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    volumes:
      - ./docker/data/postgres/auth:/var/lib/postgresql/data
    command: [ "postgres", "-c", "port=${AUTH_POSTGRES_PORT}" ]
    ports:
      - "${AUTH_POSTGRES_PORT}:${AUTH_POSTGRES_PORT}"

  cover-postgres:
    image: postgres:17
    container_name: cover-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${COVER_POSTGRES_DB}
    volumes:
      - ./docker/data/postgres/cover:/var/lib/postgresql/data
    command: [ "postgres", "-c", "port=${COVER_POSTGRES_PORT}" ]
    ports:
      - "${COVER_POSTGRES_PORT}:${COVER_POSTGRES_PORT}"

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/data/minio:/data
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_S3_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"

  visualmusic-app:
    depends_on:
      - auth-postgres
      - cover-postgres
      - minio
    image: ghcr.io/${ORG_NAME}:${SHORT_SHA}
    container_name: visualmusic-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

      AUTH_POSTGRES_URL: ${AUTH_POSTGRES_URL}
      COVER_POSTGRES_URL: ${COVER_POSTGRES_URL}
    ports:
      - "${VISUALMUSIC_APP_PORT}:8080"
