name: Deploy to Dev Server

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew :app-spring-boot:build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set short SHA to ENV
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA to ENV
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DEPLOY_SERVER_HOST }}

      - name: Copy docker-compose.yml
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_HOST }} << 'EOF'
            mkdir -p visualmusic/backend/
          EOF
          scp -o StrictHostKeyChecking=no \
            docker-compose.yml \
            ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_HOST }}:./visualmusic/backend/

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_HOST }} << 'ENDSSH'
            cat > ./visualmusic/backend/.env << 'ENDENV'
              POSTGRES_USER=${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
              AUTH_POSTGRES_DB=${{ secrets.AUTH_POSTGRES_DB }}
              AUTH_POSTGRES_PORT=${{ secrets.AUTH_POSTGRES_PORT }}
              AUTH_POSTGRES_URL=${{ secrets.AUTH_POSTGRES_URL }}
              JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
              JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
              VISUALMUSIC_APP_PORT=${{ secrets.VISUALMUSIC_APP_PORT }}
              GITHUB_USERNAME=popipopka
              REPO_NAME=${{ github.event.repository.name }}
              SHORT_SHA=${{ env.SHORT_SHA }}
            ENDENV
            
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u popipopka --password-stdin
          
            cd visualmusic/backend/
            
            docker-compose down
            docker-compose up -d
          ENDSSH